
CREATE TABLE users (
    id VARCHAR NOT NULL PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE devices (
    id VARCHAR NOT NULL PRIMARY KEY,
    name VARCHAR,
    manufacturer VARCHAR,
    user_id VARCHAR REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE parts (
    id VARCHAR NOT NULL PRIMARY KEY,
    device_id VARCHAR NOT NULL REFERENCES devices(id) ON UPDATE CASCADE ON DELETE CASCADE,
    count INTEGER,
    name VARCHAR
);

